# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather

end

target 'weather WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather WatchKit App

end

target 'weather WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather WatchKit Extension
  pod 'Alamofire'
  pod 'SwiftyJSON'
end
